# pomodoro
set -g @catppuccin_pomodoro_icon ""
set -g @pomodoro_start 'p'           # keybind to start
set -g @pomodoro_cancel 'P'          # keybind to cancel
set -g @pomodoro_mins 25
set -g @pomodoro_break_mins 5
set -g @pomodoro_notifications 'on'
set -g @pomodoro_granularity 'on'    # show minutes remaining
set -g status-interval 5                       # Refresh the status line every second


set -g @pomodoro_on "  "                      # The formatted output when the Pomodoro is running
set -g @pomodoro_complete "  "                 # The formatted output when the break is running
set -g @pomodoro_pause "  "                    # The formatted output when the Pomodoro/break is paused
set -g @pomodoro_prompt_break "  break?"      # The formatted output when waiting to start a break
set -g @pomodoro_prompt_pomodoro "  start?"   # The formatted output when waiting to start a Pomodoro
